### ISSUE TITLE
What was your prompt for CoT replies?

### ISSUE THREAD

**Issue by timothylimyl** [teknium1/GPTeacher#4]
Hi, just curious on what did you prompt to get CoT based replies.

**Comment by timothylimyl** [comment]
If you do not mind sharing, can you share how much did you spend to get the GPT4 dataset?

**Comment by teknium1** [comment]
The credits were donated so I dont know, but I used generally the same basic prompt alpaca did but asked explicitly "Where appropriate, explain your reasoning or think it out step by step", and added several examples for theory of mind, logic and reasoning problems, etc. I wouldn't say it responded exquisitely to those suggestions though, but it definitely has more instances where it adheres to those ideas than base alpaca

**Comment by timothylimyl** [comment]
Are there any reasons you could not share your `prompt.txt`?

**Comment by teknium1** [comment]
I could but it would only be the last one I used, I wasnt happy with the diversity of gens so I manually edited it a lot to add/remove categories and different ways of asking it for prompts. I might sometime soon

**Comment by timothylimyl** [comment]
I see, it will be good to see the base prompt. On the current self-instruct method, the improvements in dataset are made in the way we prompt the "oracle" model. If we can collectively improve the base prompt, I believe everyone will benefit in terms of cost saving to generate the datasets.
